/*
 *  @(#)ManagedClientAuditEventEntity.java
 *
 *  Copyright (c) Luis Antonio Mata Mata. All rights reserved.
 *
 *   All rights to this product are owned by Luis Antonio Mata Mata and may only
 *  be used under the terms of its associated license document. You may NOT
 *  copy, modify, sublicense, or distribute this source file or portions of
 *  it unless previously authorized in writing by Luis Antonio Mata Mata.
 *  In any event, this notice and the above copyright must always be included
 *  verbatim with this file.
 */
package com.umdc.persistence.general.domains;

import com.umdc.commons.general.pojo.AuditEventType;
import jakarta.persistence.*;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.UUID;

/**
 * Represents an audit event generated by a managed client in a machine-to-machine (M2M) lifecycle.
 *
 * This entity is stored in the {@code general.managed_client_audit_event} table and provides
 * information about specific actions taken by clients, their outcomes, and related metadata.
 * Each audit event is uniquely identified by a UUID and contains details about the type of event,
 * the client responsible, and additional contextual information.
 *
 * Key attributes:
 * - Primary key: {@code id}, a caller-generated UUID.
 * - Managed client: {@code clientId}, linking the event to a specific client.
 * - Event type: {@code eventType}, categorizing the event into types defined by {@link AuditEventType}.
 * - Client IP address: {@code ipAddress}, the originating address of the client.
 * - Outcome: {@code outcome}, specifying whether the action succeeded or failed.
 * - Details: {@code details}, a JSON-encoded string providing further information about the event.
 * - Timestamp: {@code occurredAt}, recording when the event occurred.
 *
 * The entity lifecycle includes the automatic setting of the {@code occurredAt} field
 * with the current timestamp when the event is first persisted.
 *
 * This class is intended for use with JPA and Hibernate to persist entity instances
 * and query audit events.
 */
@Entity
@Table(schema = "general", name = "managed_client_audit_event")
public class ManagedClientAuditEventEntity {

    /**
     * Unique identifier for the entity.
     * <p>
     * This field is annotated with {@code @Id} to denote it as the primary key
     * and {@code @Column} to configure its database column properties.
     * It is an immutable {@link UUID} value, meaning it cannot be updated after creation.
     * </p>
     */
    @Id
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    /**
     * Unique identifier for a managed client.
     *
     * Represents the UUID of the client associated with an audit event.
     * This field is mapped to the "client_id" database column.
     * It is a mandatory field and cannot be updated once it is set.
     */
    @Column(name = "client_id", nullable = false, updatable = false)
    private UUID clientId;

    /**
     * Represents the type of audit event associated with a managed client.
     *
     * This variable is mapped to the "event_type" column in the database table
     * and refers to the {@link AuditEventType} enumeration, which defines the
     * possible event classifications within the auditing system.
     *
     * Annotations:
     * - {@code @Enumerated(EnumType.STRING)}: Specifies that the enum value should
     *   be persisted as a String in the database.
     * - {@code @Column(name = "event_type", nullable = false, length = 64, updatable = false)}:
     *   Configures the database column associated with this variable, making it
     *   non-nullable, with a maximum String length of 64, and ensuring that updates
     *   to this column are disallowed post-creation.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "event_type", nullable = false, length = 64, updatable = false)
    private AuditEventType eventType;

    /**
     * Represents the IP address associated with a specific entity.
     * <ul>
     *   <li>Mapped to the database column "ip_address".</li>
     *   <li>Maximum length: 45 characters.</li>
     *   <li>This field is immutable after the initial persistence (not updatable).</li>
     * </ul>
     */
    @Column(name = "ip_address", length = 45, updatable = false)
    private String ipAddress;

    /**
     * Represents the outcome of an operation or event in the system.
     *
     * This field is a non-nullable, fixed-length (16 characters) string that documents
     * the result or status of a specific operation. It is immutable after initial creation.
     * Commonly used to track processing states or results within audit logs.
     */
    @Column(name = "outcome", nullable = false, length = 16, updatable = false)
    private String outcome;

    /**
     * Stores JSON-formatted details related to the entity.
     * <br>
     * This field is mapped to a database column of type JSONB and is not updatable after creation.
     * <br>
     * It is used to persist structured or unstructured data in JSON format, providing flexibility
     * for storing additional attributes or metadata.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "details", columnDefinition = "jsonb", updatable = false)
    private String details;

    /**
     * Represents the timestamp when an audit event occurred.
     * <p>
     * This field is mapped to the "occurred_at" column in the database.
     * It is immutable after being set, as indicated by the {@code updatable = false} property.
     * </p>
     * <p>
     * This field is mandatory and cannot be null, as specified by {@code nullable = false}.
     * It is typically used to record the precise time an event took place for audit or logging purposes.
     * </p>
     */
    @Column(name = "occurred_at", nullable = false, updatable = false)
    private LocalDateTime occurredAt;

    /**
     * Default constructor for the ManagedClientAuditEventEntity class.
     *
     * This constructor is required by Java Persistence API (JPA) to
     * instantiate objects of this entity without initializing any fields.
     * It ensures compatibility with JPA frameworks and is typically
     * used internally by the persistence provider.
     */
    public ManagedClientAuditEventEntity() {
        // JPA
    }

    /**
     * Pre-persist lifecycle callback method that is invoked by the persistence
     * context before the entity is inserted into the database.
     *
     * This method ensures that the {@code occurredAt} field is populated with the
     * current timestamp if it has not been set already. The {@code occurredAt} field
     * typically represents the date and time when the audit event occurred.
     */
    @PrePersist
    public void prePersist() {
        if (occurredAt == null) {
            occurredAt = LocalDateTime.now(ZoneId.systemDefault());
        }
    }

    // -------------------------------------------------------------------------
    // Getters and setters
    // -------------------------------------------------------------------------

    /**
     * Retrieves the unique identifier associated with this entity.
     *
     * @return the UUID representing the unique identifier
     */
    public UUID getId() {
        return id;
    }

    /**
     * Sets the primary key.
     *
     * @param id the UUID id
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Returns the managed client ID that triggered this event.
     *
     * @return the clientId
     */
    public UUID getClientId() {
        return clientId;
    }

    /**
     * Sets the managed client ID.
     *
     * @param clientId the clientId
     */
    public void setClientId(UUID clientId) {
        this.clientId = clientId;
    }

    /**
     * Returns the event type discriminator.
     *
     * @return the eventType
     */
    public AuditEventType getEventType() {
        return eventType;
    }

    /**
     * Sets the event type discriminator.
     *
     * @param eventType the eventType
     */
    public void setEventType(AuditEventType eventType) {
        this.eventType = eventType;
    }

    /**
     * Returns the client IP address.
     *
     * @return the ipAddress
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Sets the client IP address.
     *
     * @param ipAddress the ipAddress
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Returns the outcome string (SUCCESS or FAILURE).
     *
     * @return the outcome
     */
    public String getOutcome() {
        return outcome;
    }

    /**
     * Sets the outcome string.
     *
     * @param outcome the outcome
     */
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    /**
     * Returns the JSON details string.
     *
     * @return the details
     */
    public String getDetails() {
        return details;
    }

    /**
     * Sets the JSON details string.
     *
     * @param details the details
     */
    public void setDetails(String details) {
        this.details = details;
    }

    /**
     * Returns the timestamp when the event occurred.
     *
     * @return the occurredAt
     */
    public LocalDateTime getOccurredAt() {
        return occurredAt;
    }

    /**
     * Sets the timestamp when the event occurred.
     *
     * @param occurredAt the occurredAt
     */
    public void setOccurredAt(LocalDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }
}

