variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
qodana:
  only:
    - merge_requests
    - master
    - develop
  image:
    name: jetbrains/qodana-jvm-community:2023.2
    entrypoint: [""]
  cache:
    - key: qodana-2023.2-$CI_DEFAULT_BRANCH-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - qodana-2023.2-$CI_DEFAULT_BRANCH-
        - qodana-2023.2-
      paths:
        - .qodana/cache
  variables:
    QODANA_TOKEN: $QODANA_TOKEN
  script:
    - qodana --cache-dir=$CI_PROJECT_DIR/.qodana/cache
  artifacts:
    paths:
      - qodana/report/
    expose_as: 'Qodana report'
sonarcloud-check:
  image: maven:3.9.0-amazoncorretto-17 # Or newer
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.organization=prx-open -Dsonar.projectKey=com.prx:persistence -s ci_settings.xml
  only:
    - merge_requests
    - master
    - develop
